language: node_js
services:
  - postgresql
cache:
  directories:
    - "node_modules"
  yarn: true
node_js:
  - "8"
before_script:
  - cp ormconfig.json.example ormconfig.json
  - yarn lint
script: yarn test-coverage -i
