language: node_js
services:
  - postgresql
cache:
  directories:
    - "node_modules"
  yarn: true
node_js:
  - "8"
before_script:
  - psql -c 'create database nodesrvtest;' -U postgres
  - cp ormconfig-travis.json ormconfig.json
  - yarn lint
script: yarn test-coverage -i
