version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: nodesrv
  
  app:
    build: .
    ports:
      - "5151:5151"
    depends_on:
      - db
    working_dir: "/app"
    volumes:
      - .:/app
    entrypoint: npm run start 08a2bc9b-679a-4bee-85d0-127288a24f61 5151