import { AffectType } from "../../affect/enum/affectType"

export const itemAffectMap = {
  A: AffectType.Glow,
  B: AffectType.Hum,
  C: AffectType.ImmortalLoad,
  D: AffectType.Lock,
  E: AffectType.Evil,
  F: AffectType.Invisible,
  G: AffectType.Magic,
  H: AffectType.NoDrop,
  I: AffectType.Bless,
  J: AffectType.AntiGood,
  K: AffectType.AntiEvil,
  L: AffectType.AntiNeutral,
  M: AffectType.NoRemove,
  N: AffectType.Inventory,
  O: AffectType.NoPurge,
  P: AffectType.RotDeath,
  Q: AffectType.VisDeath,
  R: AffectType.NoSacrifice,
  S: AffectType.NonMetal,
  T: AffectType.NoLocate,
  U: AffectType.MeltDrop,
  V: AffectType.HasTimer,
  W: AffectType.SellExtract,
  X: AffectType.WearTimer,
  Y: AffectType.BurnProof,
  Z: AffectType.NounCurse,
  aa: AffectType.ClanCorpse,
  bb: AffectType.Warped,
  cc: AffectType.Teleport,
  dd: AffectType.NoIdentify,
}
