export enum Equipment {
  Head = "head",
  Torso = "torso",
  Arms = "arms",
  Legs = "legs",
  Weapon = "weapon",
  Shield = "shield",
  Held = "held",
  Finger = "finger",
  Neck = "neck",
  Feet = "feet",
  Hands = "hands",
  About = "about",
  Waist = "waist",
  Wrist = "wrist",
  Hold = "hold",
  Float = "float",
  Dragging = "dragging",
}
