export enum WeaponEffect {
  Flaming = "flaming",
  Frost = "frost",
  Vampiric = "vampiric",
  Vorpal = "vorpal",
  Shocking = "shocking",
  Poison = "poison",
  Stun = "stun",
  Holy = "holy",
  Favored = "favored",
  Nether = "nether",
  Scion = "scion",
  Sharp = "sharp",
  ResistEnchant = "resist enchant",
}
