export enum AffectType {
  AntiEvil = "anti-evil",
  AntiGood = "anti-good",
  AntiNeutral = "anti-neutral",
  Bless = "bless",
  Berserk = "berserk",
  Blind = "blind",
  BurnProof = "burn proof",
  ClanCorpse = "clan corpse",
  Curse = "curse",
  DetectInvisible = "detect invisible",
  DetectHidden = "detect hidden",
  GiantStrength = "giant strength",
  Glow = "glow",
  Hum = "hum",
  ImmortalLoad = "imm",
  Lock = "lock",
  Evil = "evil",
  HasTimer = "has timer",
  Invisible = "invisible",
  Magic = "magic",
  MeltDrop = "melt drop",
  NoDrop = "no drop",
  NoIdentify = "no identify",
  NoLocate = "no locate",
  NoRemove = "no remove",
  NoPurge = "no purge",
  NoSacrifice = "no sacrifice",
  NonMetal = "non-metal",
  NounCurse = "noun curse",
  Poison = "poison",
  RotDeath = "rot death",
  VisDeath = "vis death",
  SellExtract = "sell extract",
  Stunned = "stunned",
  Sharpened = "sharpened",
  Shield = "shield",
  Sneak = "sneak",
  Teleport = "teleport",
  Warped = "warped",
  WearTimer = "wear timer",
  Wrath = "wrath",

  // testing
  Noop = "noop",

  // import
  Inventory = "inventory",
}
