export const CreationMessages = {
  All: {
    ConfirmFailed: "Please respond with 'y' or 'n'.",
    Done: "Done.",
    NotFound: "That was not found.",
    Ok: "Ok",
  },
  Mob: {
    AlreadyKnown: "You already know {0}.",
    Confirm: "New mob. Are you sure?",
    CustomizeCheck: "Do you want to customize?",
    CustomizeFail: "Not understood.",
    CustomizePrompt: "Customization command (add/remove/list/done/help): ",
    Help: "Help tbd",
    NamePrompt: "By what name do you wish to be known?",
    NameUnavailable: "That name is unavailable, try something else",
    NotKnown: "You don't know {0}.",
    RaceInvalid: "That is not a valid race.",
    RacePrompt: "Choose a race.",
    SpecializationInvalid: "That is not a valid specialization.",
    SpecializationPrompt: "Choose a specialization [{0} ].",
  },
  Player: {
    Confirm: "New player. Are you sure?",
    EmailInvalid: "That does not appear to be an email address.",
    EmailPrompt: "Email address:",
    LoginFailed: "Login failed.",
    PasswordConfirm: "Enter password one more time:",
    PasswordMismatch: "Passwords do not match.",
    PasswordPrompt: "Password:",
    PasswordTooShort: "Password is too short.",
    PlayerDone: "Done. By what name do you wish to be known?",
  },
}
