export enum ActionPart {
  Action = "action",
  Thing = "thing",
  Spell = "spell",
  Skill = "skill",
  ItemInInventory = "item in inventory",
  ItemInEquipment = "item in equipment",
  ItemWithRoomMob = "item with room mob",
  ItemInRoom = "item in room",
  Target = "target",
  Hostile = "hostile",
  PlayerMob = "player mob",
  LoggedInMob = "logged in mob",
  MobInArea = "mob in area",
  MobInRoom = "mob in room",
  FreeForm = "free form",
  Number = "number",
  GoldOnHand = "gold on hand",
  ShortName = "short name",
  CCNumber = "credit card number",
  ExpMonth = "exp month",
  ExpYear = "exp year",
}
