export enum ActionPart {
  Action = "action",
  Thing = "thing",
  Spell = "spell",
  Skill = "skill",
  ItemInInventory = "item in inventory",
  ItemInEquipment = "item in equipment",
  ItemWithRoomMob = "item with room mob",
  ItemInRoom = "item in room",
  Target = "target",
  PlayerMob = "player mob",
  LoggedInMob = "logged in mob",
  MobInArea = "mob in area",
  FreeForm = "free form",
  Number = "number",
}
