export enum RaceType {
  Human = "human",
  Dwarf = "dwarf",
  Elf = "elf",
  Drow = "drow",
  Kender = "kender",
  Halfling = "halfling",
  Gnome = "gnome",
  Goblin = "goblin",
  Faerie = "faerie",
  HalfOrc = "half-orc",
  Ogre = "ogre",
  Giant = "giant",

  // Nonplayable
  Insect = "insect",
  Bat = "bat",
  Bird = "bird",
  Bear = "bear",
  Cat = "cat",
  Dog = "dog",
  Fox = "fox",
  Lizard = "lizard",
  Hobgoblin = "hobgoblin",
  Kobold = "kobold",
  Orc = "orc",
  Hog = "pig",
  Rabit = "rabit",
  Snake = "snake",
  Troll = "troll",
  WaterFoul = "water foul",
  Wolf = "wolf",
  Wvyern = "wvyern",
  Critter = "critter",
  Undead = "undead",
}
