export enum RequestType {
    Gossip = "gossip",
    Get = "get",
    Drop = "drop",
    Inventory = "inventory",
    Look = "look",
    North = "north",
    South = "south",
    East = "east",
    West = "west",
    Up = "up",
    Down = "down",
    Wear = "wear",
    Remove = "remove",
    Equipped = "equipped",
    Kill = "kill",
    Bash = "bash",
    Cast = "cast",
    Affects = "affects",
    Trip = "trip",
    Sneak = "sneak",
    Berserk = "berserk",
    Buy = "buy",
    Sell = "sell",
    Noop = "noop",
    Any = "any",
}
