export enum RequestType {
  Gossip = "gossip",
  Say = "say",
  Get = "get",
  Drop = "drop",
  Inventory = "inventory",
  Look = "look",
  North = "north",
  South = "south",
  East = "east",
  West = "west",
  Up = "up",
  Down = "down",
  Wear = "wear",
  Remove = "remove",
  Equipped = "equipped",
  Kill = "kill",
  Flee = "flee",
  Bash = "bash",
  Cast = "cast",
  Affects = "affects",
  Trip = "trip",
  Sneak = "sneak",
  Berserk = "berserk",
  Buy = "buy",
  Sell = "sell",
  Sleep = "sleep",
  Wake = "wake",
  Train = "train",
  Practice = "practice",
  Score = "score",
  Eat = "eat",
  Noop = "noop",
  Any = "any",

  // greater than mortal
  Ban = "ban",
  Unban = "unban",
}
