export enum SkillType {
   // tested
  Bash = "bash",
  Trip = "trip",
  Sneak = "sneak",
  Berserk = "berserk",
  Dodge = "dodge",
  Disarm = "disarm",
  Backstab = "backstab",
  SecondAttack = "second attack",
  DirtKick = "dirt kick",
  FastHealing = "fast healing",
  Envenom = "envenom",
  EnhancedDamage = "enhanced damage",

  // implementation not needed?
  Infravision = "infravision",

  // planned
  Parry = "parry",
  ThirdAttack = "third attack",
  FourthAttack = "fourth attack",
  Haggle = "haggle",
  Meditation = "meditation",
  Throw = "throw",
  Bite = "bite",
  DualWield = "dual wield",
  Hamstring = "hamstring",
  Garotte = "garotte",
  HandToHand = "hand to hand",
  Kick = "kick",
  ShieldBash = "shield bash",
  ShieldBlock = "shield block",
  Scan = "scan",
  Hide = "hide",
  Lore = "lore",
  Peek = "peek",
  Sharpen = "sharpen",
  Shout = "shout",
  Slice = "slice",
  Spellcraft = "spellcraft",
  Steal = "steal",
  Flying = "flying",

  // weapons
  Sword = "sword",
  Axe = "axe",
  Dagger = "dagger",
  Mace = "mace",
  Flail = "flail",
  Stave = "stave",
  Wand = "wand",
  Polearm = "polearm",
  Spear = "spear",
  Whip = "whip",

  Noop = "noop",
}
