export enum DamageSourceFlag {
  Summon = "A",
  Charm = "B",
  Magic = "C",
  Weapon = "D",
  Bash = "E",
  Pierce = "F",
  Slash = "G",
  Fire = "H",
  Cold = "I",
  Lightning = "J",
  Acid = "K",
  Poison = "L",
  Negative = "M",
  Holy = "N",
  Energy = "O",
  Mental = "P",
  Disease = "Q",
  Drowning = "R",
  Light = "S",
  Sound = "T",
  Wood = "X",
  Silver = "Y",
  Iron = "Z",
  Distraction = "a",
}
