export enum ItemType {
  Weapon = "weapon",
  Armor = "armor",
  Clothing = "clothing",
  Boat = "boat",
  Container = "container",
  Drink = "drink",
  Food = "food",
  Fountain = "fountain",
  Forge = "forge",
  Gem = "gem",
  Potion = "potion",
  Light = "light",
  Map = "map",
  Trash = "trash",
  Key = "key",
  Wand = "wand",
  SpellPage = "spell_page",
  ItemPart = "item_part",
  Furniture = "furniture",
  Money = "money",
}
