export enum MobOffensiveTrait {
  AreaAttack = "A",
  Backstab = "B",
  Bash = "C",
  Berserk = "D",
  Disarm = "E",
  Dodge = "F",
  Fade = "G",
  Fast = "H",
  Kick = "I",
  KickDirt = "J",
  Parry = "K",
  Rescue = "L",
  Tail = "M",
  Trip = "N",
  Crush = "O",
  AssistAll = "P",
  AssistAlign = "Q",
  AssistRace = "R",
  AssistPlayers = "S",
  AssistGuard = "T",
  AssistVnum = "U",
  OffCharge = "V",
  AssistElement = "W",
}
