export enum MobTrait {
  IsNpc = "A",
  Sentinel = "B",
  Scavenger = "C",
  Aggressive = "F",
  StayArea = "G",
  Wimpy = "H",
  Pet = "I",
  Trainer = "J",
  Practice = "K",
  Undead = "O",
  Weaponsmith = "P",
  Armorer = "X",
  Cleric = "Q",
  Mage = "R",
  Ranger = "S",
  Warrior = "T",
  NoAlign = "U",
  NoPurge = "V",
  Outdoors = "W",
  Indoors = "Y",
  Mount = "Z",
  Healer = "a",
  Gain = "b",
  UpdateAlways = "c",
  Changer = "d",
  NoTrans = "e",
}
